# Generated by Django 6.0.4 on 2026-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
