# Generated by Django 6.0.4 on 2026-04-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuario_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='corazones_vaciados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='corazones',
            field=models.IntegerField(default=5),
        ),
    ]
