# Generated by Django 6.0.4 on 2026-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usuario_corazones_vaciados_en_usuario_es_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='node_class_completada',
            field=models.BooleanField(default=False),
        ),
    ]
